### ISSUE TITLE
sysmsg

### ISSUE THREAD

**Issue by Owyn** [pinkipi/auto-negotiate#8]
I've been told 
`const msg = dispatch.parseSystemMessage(event)`
should be
`const msg = dispatch.base.parseSystemMessage(event)`

🤔

**Comment by pinkipi** [comment]
Either works since those functions are exported in DispatchWrapper (same as in Caali's fork of tera-proxy-game).

That said, it should be `dispatch.parseSystemMessage(event.message)`. I've fixed that typo now.
